### ISSUE TITLE
ImportError: No module named bs4

### ISSUE THREAD

**Issue by DaxChen** [invicnaper/spotify-dl#1]
Sorry I'm new to python

I have `youtube-dl` installed and did `pip install beautifulsoup4`

but when I run `./spotify-dl.py --track spotify:track:23L5CiUhw2jV1OIMwthR3S --dl youtube`

I get the following error:

```
Traceback (most recent call last):
  File "./spotify-dl.py", line 9, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
```

Thank you!

> I'm on `macOS 10.11.6`
> `Python 2.7.12`
> `pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)`

**Comment by lobosmal** [comment]
i got the script working by reinstalling bs4 like this:

sudo  pip install beautifulsoup4

in my case without the sudo command pip does not install everything

**Comment by invicnaper** [comment]
Yep try installing bs4 using sudo

**Comment by agentf90** [comment]
I had to add `#!/usr/bin/env python2.7`  to the top of the script.
