### ISSUE TITLE
How to download a playlist

### ISSUE THREAD

**Issue by hhlp** [invicnaper/spotify-dl#13]
I follow this step : https://github.com/invicnaper/spotify-dl/issues/9

but when I try to download a playlist I get the following error :

@ spotify-dl.py version 0.0.1
@ author : Naper
@ Designed for OSx/linux

[+]  getting track name
[+] can't found song name
[+] non existing id
[+] An HTTP error occurred

I execute the command like this :

./spotify-dl --track {spotify_song_id} --dl youtube --access_token <your_access_token>

Regards.,

**Comment by invicnaper** [comment]
Are you sure about the song's ID ?
